// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package endpoint

import (
	endpoint "github.com/go-kit/kit/endpoint"
	service "github.com/goforbroke1006/teamtrack/pkg/service"
)

// Endpoints collects all of the endpoints that compose a profile service. It's
// meant to be used as a helper struct, to collect all of the endpoints into a
// single parameter.
type Endpoints struct {
	FooEndpoint      endpoint.Endpoint
	BarEndpoint      endpoint.Endpoint
	WildfowlEndpoint endpoint.Endpoint
}

// New returns a Endpoints struct that wraps the provided service, and wires in all of the
// expected endpoint middlewares
func New(s service.TeamtrackService, mdw map[string][]endpoint.Middleware) Endpoints {
	eps := Endpoints{
		BarEndpoint:      MakeBarEndpoint(s),
		FooEndpoint:      MakeFooEndpoint(s),
		WildfowlEndpoint: MakeWildfowlEndpoint(s),
	}
	for _, m := range mdw["Foo"] {
		eps.FooEndpoint = m(eps.FooEndpoint)
	}
	for _, m := range mdw["Bar"] {
		eps.BarEndpoint = m(eps.BarEndpoint)
	}
	for _, m := range mdw["Wildfowl"] {
		eps.WildfowlEndpoint = m(eps.WildfowlEndpoint)
	}
	return eps
}
