version: "3"
services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    restart: always
    volumes:
      - .:/go/src/github.com/goforbroke1006/teamtrack
    ports:
      - 8800:8081
    depends_on:
      - db
      - consul

  db:
    image: postgres:11.1
    environment:
      POSTGRES_DB: teamtrack_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456

  consul:
    build:
      context: .
      dockerfile: ./docker/consul/Dockerfile
    hostname: localhost
    ports:
      - 8500:8500
    restart: always
    volumes:
      - ${PWD}/.consul:/consul-initial/.consul
