version: "3"
services:
#  app:
#    build:
#      context: .
#      dockerfile: ./docker/app/Dockerfile
#    restart: always
#    volumes:
#      - .:/go/src/github.com/goforbroke1006/teamtrack
#    ports:
#      - 8800:8081
#    environment:
#      DB_HOST: db
#      DB_PORT: 5432
#      DB_NAME: teamtrack_db
#      DB_USER: root
#      DB_PASS: 123456
#    depends_on:
#      - db

  db:
    image: postgres:11.1
    environment:
      POSTGRES_DB: teamtrack_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
    ports:
      - 54321:5432
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: