// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package http

import (
	http "github.com/go-kit/kit/transport/http"
	endpoint "github.com/goforbroke1006/teamtrack/pkg/endpoint"
	http1 "net/http"
)

//  NewHTTPHandler returns a handler that makes a set of endpoints available on
// predefined paths.
func NewHTTPHandler(endpoints endpoint.Endpoints, options map[string][]http.ServerOption) http1.Handler {
	m := http1.NewServeMux()
	makeCreateTeamHandler(m, endpoints, options["CreateTeam"])
	makeJoinTeamHandler(m, endpoints, options["JoinTeam"])
	makeSetPositionHandler(m, endpoints, options["SetPosition"])
	makeGetMatesPositionsHandler(m, endpoints, options["GetMatesPositions"])
	return m
}
