// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package service

import (
	endpoint1 "github.com/go-kit/kit/endpoint"
	log "github.com/go-kit/kit/log"
	prometheus "github.com/go-kit/kit/metrics/prometheus"
	opentracing "github.com/go-kit/kit/tracing/opentracing"
	http "github.com/go-kit/kit/transport/http"
	endpoint "github.com/goforbroke1006/teamtrack/pkg/endpoint"
	http1 "github.com/goforbroke1006/teamtrack/pkg/http"
	service "github.com/goforbroke1006/teamtrack/pkg/service"
	group "github.com/oklog/oklog/pkg/group"
	opentracinggo "github.com/opentracing/opentracing-go"
)

func createService(endpoints endpoint.Endpoints) (g *group.Group) {
	g = &group.Group{}
	initHttpHandler(endpoints, g)
	return g
}
func defaultHttpOptions(logger log.Logger, tracer opentracinggo.Tracer) map[string][]http.ServerOption {
	options := map[string][]http.ServerOption{
		"Bar":      {http.ServerErrorEncoder(http1.ErrorEncoder), http.ServerErrorLogger(logger), http.ServerBefore(opentracing.HTTPToContext(tracer, "Bar", logger))},
		"Foo":      {http.ServerErrorEncoder(http1.ErrorEncoder), http.ServerErrorLogger(logger), http.ServerBefore(opentracing.HTTPToContext(tracer, "Foo", logger))},
		"Wildfowl": {http.ServerErrorEncoder(http1.ErrorEncoder), http.ServerErrorLogger(logger), http.ServerBefore(opentracing.HTTPToContext(tracer, "Wildfowl", logger))},
	}
	return options
}
func addDefaultEndpointMiddleware(logger log.Logger, duration *prometheus.Summary, mw map[string][]endpoint1.Middleware) {
	mw["Foo"] = []endpoint1.Middleware{endpoint.LoggingMiddleware(log.With(logger, "method", "Foo")), endpoint.InstrumentingMiddleware(duration.With("method", "Foo"))}
	mw["Bar"] = []endpoint1.Middleware{endpoint.LoggingMiddleware(log.With(logger, "method", "Bar")), endpoint.InstrumentingMiddleware(duration.With("method", "Bar"))}
	mw["Wildfowl"] = []endpoint1.Middleware{endpoint.LoggingMiddleware(log.With(logger, "method", "Wildfowl")), endpoint.InstrumentingMiddleware(duration.With("method", "Wildfowl"))}
}
func addDefaultServiceMiddleware(logger log.Logger, mw []service.Middleware) []service.Middleware {
	return append(mw, service.LoggingMiddleware(logger))
}
func addEndpointMiddlewareToAllMethods(mw map[string][]endpoint1.Middleware, m endpoint1.Middleware) {
	methods := []string{"Foo", "Bar", "Wildfowl"}
	for _, v := range methods {
		mw[v] = append(mw[v], m)
	}
}
