// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package service

import (
	endpoint1 "github.com/go-kit/kit/endpoint"
	log "github.com/go-kit/kit/log"
	prometheus "github.com/go-kit/kit/metrics/prometheus"
	opentracing "github.com/go-kit/kit/tracing/opentracing"
	http "github.com/go-kit/kit/transport/http"
	endpoint "github.com/goforbroke1006/teamtrack/pkg/endpoint"
	http1 "github.com/goforbroke1006/teamtrack/pkg/http"
	service "github.com/goforbroke1006/teamtrack/pkg/service"
	group "github.com/oklog/oklog/pkg/group"
	opentracinggo "github.com/opentracing/opentracing-go"
)

func createService(endpoints endpoint.Endpoints) (g *group.Group) {
	g = &group.Group{}
	initHttpHandler(endpoints, g)
	return g
}
func defaultHttpOptions(logger log.Logger, tracer opentracinggo.Tracer) map[string][]http.ServerOption {
	options := map[string][]http.ServerOption{
		"CreateTeam":        {http.ServerErrorEncoder(http1.ErrorEncoder), http.ServerErrorLogger(logger), http.ServerBefore(opentracing.HTTPToContext(tracer, "CreateTeam", logger))},
		"GetMatesPositions": {http.ServerErrorEncoder(http1.ErrorEncoder), http.ServerErrorLogger(logger), http.ServerBefore(opentracing.HTTPToContext(tracer, "GetMatesPositions", logger))},
		"JoinTeam":          {http.ServerErrorEncoder(http1.ErrorEncoder), http.ServerErrorLogger(logger), http.ServerBefore(opentracing.HTTPToContext(tracer, "JoinTeam", logger))},
		"SetPosition":       {http.ServerErrorEncoder(http1.ErrorEncoder), http.ServerErrorLogger(logger), http.ServerBefore(opentracing.HTTPToContext(tracer, "SetPosition", logger))},
	}
	return options
}
func addDefaultEndpointMiddleware(logger log.Logger, duration *prometheus.Summary, mw map[string][]endpoint1.Middleware) {
	mw["CreateTeam"] = []endpoint1.Middleware{endpoint.LoggingMiddleware(log.With(logger, "method", "CreateTeam")), endpoint.InstrumentingMiddleware(duration.With("method", "CreateTeam"))}
	mw["JoinTeam"] = []endpoint1.Middleware{endpoint.LoggingMiddleware(log.With(logger, "method", "JoinTeam")), endpoint.InstrumentingMiddleware(duration.With("method", "JoinTeam"))}
	mw["SetPosition"] = []endpoint1.Middleware{endpoint.LoggingMiddleware(log.With(logger, "method", "SetPosition")), endpoint.InstrumentingMiddleware(duration.With("method", "SetPosition"))}
	mw["GetMatesPositions"] = []endpoint1.Middleware{endpoint.LoggingMiddleware(log.With(logger, "method", "GetMatesPositions")), endpoint.InstrumentingMiddleware(duration.With("method", "GetMatesPositions"))}
}
func addDefaultServiceMiddleware(logger log.Logger, mw []service.Middleware) []service.Middleware {
	return append(mw, service.LoggingMiddleware(logger))
}
func addEndpointMiddlewareToAllMethods(mw map[string][]endpoint1.Middleware, m endpoint1.Middleware) {
	methods := []string{"CreateTeam", "JoinTeam", "SetPosition", "GetMatesPositions"}
	for _, v := range methods {
		mw[v] = append(mw[v], m)
	}
}
